# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20170913_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='put_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
